### ISSUE TITLE
bmi percentiles (bmip) generated with ext_bmiz don't match up with NHANES child BMI categories

### ISSUE THREAD

**Issue by jaskdb** [carriedaymont/growthcleanr#133]
Hello, I am working on getting the BMI percentiles for youth in NHANES cycles where the BMI category (BMDBMIC, which codes for under/normal/overweight/ obese) variable did not exist. I have tried both this package as well as `cdcanthro` which result in the same findings:

I am finding that the BMI percentiles do not match to what I expected when comparing to the BMDBMIC variable in NHANES. For example, according to the BMI category variable for underweight (BMDBMIC == 1), I would expect to only find that individuals in that category would have **bmip** of less than 5, but I find that it includes some participants with percentiles up to 9.85. Similarly, for the normal weight category, BMDBMIC == 2, where I would not expect **bmip** above 85, I find that there are participants with percentiles as high as 88.  Any ideas why?

Code for reproducible example:
#download data from nhanes 2011-12 (cycle G). if necessary: install.packages("nhanesA")
`library(nhanesA)` #nhanesA package pulls questionnaire data from cdc website
`library(tidyverse)`
`bmi_g <- nhanes('BMX_G') %>% select(SEQN, BMXBMI, BMDBMIC, BMXHT,BMXWT)` 
`demo_g <- nhanes('DEMO_G') %>% select(SEQN,RIDEXAGM, DMDHRGND)`
`test <- merge(bmi_g, demo_g, by= "SEQN")`

#remove NAs and recode sex
`nhanes <- test %>% filter(!is.na(test$BMXBMI) & !is.na(test$RIDEXAGM))` 
`nhanes$agemos <- nhanes$RIDEXAGM + 0.5` # because agemos is completed number of months
`nhanes$sex <- ifelse(nhanes$DMDHRGND == 1, "male", "female")`
`nhanes$sex <- as.factor(nhanes$sex)`

#run ext_bmiz function
`cleaned_data_bmiz <- ext_bmiz(nhanes, age = "agemos", wt = "BMXWT", ht = "BMXHT", bmi = "BMXBMI")`

**Comment by CDC-DNPAO** [comment]
Hello Jaskdb.  I'm David Freedman at CDC and wrote the code for calculating the BMI percentiles/z-scores.  The problem is that you're using the wrong 'sex' variable - the one you're using is the sex of the head of the household.  If you use RIAGENDR (also coded 1/2 for boys/girls in the DEMO file), you'll find that the results agree with BMIBMIC.
