### ISSUE TITLE
Additional z-scores for lightness and height-to-mass ratio 

### ISSUE THREAD

**Issue by kliegl** [carriedaymont/growthcleanr#146]
Not a bug report, but a feature request for ext_bmiz(..., lt="lt", hmr="hmr", ...)

Would it be possible to provide age- and sex-adjusted z-scores and percentiles also for:

(1) lightness = 1 / weight
(2) height-to-mass ratio = height/weight ?

Reason: I would like to replace the transformations used in this paper with age-/sex-adjusted z-scores.
https://www.researchgate.net/publication/377692841_Impact_of_Height-to-Mass_Ratio_on_Physical_Fitness_of_German_Third-Grade_Children.

Thank you.

**Comment by carriedaymont** [comment]
Hello,

Thank you very much for your interest in growthcleanr. Unfortunately, there is a long list of updates/improvements I would like to make to growthcleanr and limited time and money. I don't foresee having the bandwidth to add additional parameters. 

Best,
Carrie
