### ISSUE TITLE
Verify quietly option

### ISSUE THREAD

**Issue by dchud** [carriedaymont/growthcleanr#21]
Report from MacOS:

> The 'quietly' argument is somehow screwy:  if parallel = TRUE then quietly can be either TRUE or FALSE.  But if parallel = TRUE and quietly is set to F [not FALSE], the program bombs with the error: Error in !quietly : invalid argument type.

**Comment by delosh653** [comment]
Turned out to be a user-specific "confounding objects in environment" issue. Fixed when environment was cleared.
