### ISSUE TITLE
NHANES reference data has multiple agedays==23 entries

### ISSUE THREAD

**Issue by dchud** [carriedaymont/growthcleanr#40]
See following lines:

- https://github.com/carriedaymont/growthcleanr/blob/main/inst/extdata/nhanes-reference-medians.csv#L25
- https://github.com/carriedaymont/growthcleanr/blob/main/inst/extdata/nhanes-reference-medians.csv#L14637
- https://github.com/carriedaymont/growthcleanr/blob/main/inst/extdata/nhanes-reference-medians.csv#L7331
- https://github.com/carriedaymont/growthcleanr/blob/main/inst/extdata/nhanes-reference-medians.csv#L21943

Each of those rows duplicates the sex/param/agedays above. There should only be only value for each sex/param/agedays combination.

It looks like the weights are stable, so that should be an easy fix. The heights vary across the duplicate entries, though, which needs resolution.

**Comment by dxf1david** [comment]
hey - I've never left a comment on github!  One estimated represent the smoothed value and the other the unsmoothed value - this was for heights.  But when I merged it with weights, it duplicated the weights.  I sent Dan a new corrected CSV file
