### ISSUE TITLE
Errors processing adult data

### ISSUE THREAD

**Issue by dchud** [carriedaymont/growthcleanr#53]
Processing a large dataset in ~10k sets of ~30k measurements, ran into a few errors.

- [x] "best_w2-not-none-arg-len", in about 100 separate files, with full error text:

```R
Error in if (best_w2 != "none") { : argument is of length zero
Calls: [ ... [.data.table -> eval -> eval -> cleangrowth -> cleanadult
```

- [x] "binerr_interpol-arg-type", in 2 files, with error text:

```R
Error in !binerr_interpol : invalid argument type
Calls: [ ... [.data.table -> eval -> eval -> cleangrowth -> cleanadult
```

- [x] "if-all-not-criteria_new" in 2 files, with error text:

```R
Error in if (all(!criteria_new)) { :
  missing value where TRUE/FALSE needed
Calls: [ ... [.data.table -> eval -> eval -> cleangrowth -> cleanadult
```

Example files exhibiting these issues shared separately.

Also confirmed that these same errors occur on multiple platforms: linux and macos.

**Comment by delosh653** [comment]
I think the third error was fixed when I fixed the second (they happen in the same code block), but let me know if it's not fixed.

**Comment by dchud** [comment]
This was completed in https://github.com/mitre/growthcleanr/pull/20.
