### ISSUE TITLE
longwide() does not keep dates

### ISSUE THREAD

**Issue by dchud** [carriedaymont/growthcleanr#71]
The utility function `longwide()` appears to drop dates on input data. It might be helpful to include them in the data returned, to save the hassle of having to re-join data to dates after this step.

The test suite uses `syngrowth`, which does not have dates.

- [ ] make change to function and parameters
- [ ] update function docs in `R/utils.R`
- [ ] update utilities vignette at `vignettes/utilities.Rmd` with examples using new option
- [ ] check quickstart and other vignettes for other references that might require updates
- [ ] rebuild [pkgdown](https://pkgdown.r-lib.org/) docs

**Comment by molivier-314** [comment]
Update 10/18: working on this.

**Comment by dchud** [comment]
Closed by #111.
